### ISSUE TITLE
Bauanleitung Gestur3Bot

### ISSUE THREAD

**Issue by cf2342** [robodhhb/Gestur3Bot#2]
Dank Ausgangsbeschränkung habe ich endlich Zeit, ein paar Projekte auszuprobieren. Unter anderem habe ich dieses schöne Projekt nachgebaut. Danke dafür.
Dabei bin ich allerdings auf einen Fehler gestossen, den ich anderen ersparen möchte. ;)

Ich wunderte mich beim ersten Test, warum der Befehl zum schliessen des Greifarms nicht funktionierte, obwohl er richtig erkannt wurde und erfuhr erst nach einem Blick in den Code, dass Mission 04 auch gebaut werden muss, aber anstatt wie in der Lego-Anleitung muss der Tastsensor nicht in Port 1, sondern in Port 2 gesteckt werden.
Vielleicht kann man das noch ergänzen.

**Comment by robodhhb** [comment]
Hallo cf2342,
vielen Dank für den Hinweis. Ich ergänze die Bauanleitung um einen Hinweis.
